Update ipol.py
wradlib/wradlib pull request #576
Opened 2022-06-07 05:28 UTC by syedhamidali

changed np.arange(0,360, 360/data.shape[0]) to np.linspace(0,360,data.shape[0]). Because np.arange changes the shape of the array if the number is even. e.g., if the data is having a shape of 643, 2500 (azis, rngs), and doing np.arange(0, 360, 360.0 / 644).shape will give us the shape 645. This throws then error because it doesn't match with original array and therefore interpolation can't be done.

2022-06-07 06:39 UTC, kmuehlbauer requested changes
@syedhamidali Thanks for catching this corner case. There are only 27 cases for shapes up to 1000 where this behaviour manifests (due to rounding effects).

Citing from [numpy.arange documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html):

```
stop : integer or real

    End of interval. The interval does not include this value, except
    in some cases where step is not an integer and floating point
    round-off affects the length of out.
```

We need to change one thing though (see inline comment). It would be great if you could add a test, if possible.

2022-06-07 06:39 UTC, kmuehlbauer commented on wradlib/ipol.py
> +    # angles = np.repeat(
Just remove the commented lines, they are not needed any more.

2022-06-07 06:42 UTC, kmuehlbauer commented
@syedhamidali You'll need to fix the linting errors before CI will test the changes.

2022-06-07 19:47 UTC, syedhamidali commented on wradlib/ipol.py
> +        np.radians(np.linspace(0, 360, data.shape[0])), data.shape[1]
Okay, I have tried to get rid of linting errors. You may have a look now. Thanks!

2022-06-08 05:57 UTC, kmuehlbauer commented on wradlib/ipol.py
> +        np.radians(np.linspace(0, 360, data.shape[0])), data.shape[1]
@syedhamidali Thanks for fixing this. I've just fixed the black style issue.

I'm considering adding pre-commit hooks to wradlib for a more contributor friendly style/lint handling.

2022-06-08 05:58 UTC, kmuehlbauer approved these changes

2022-06-08 06:00 UTC, merged

2022-06-08 06:05 UTC, kmuehlbauer commented
Thanks @syedhamidali! Looks like this is (beside your activity here and on wradlib-user list) your first contribution to wradlib codebase. :clap: